### ISSUE TITLE
Unable to run on ubuntu 18.10

### ISSUE THREAD

**Issue by choman** [ehough/docker-nfs-server#23]
First off I think this project is pretty cool, and I hope it helps me with my current problem

Anyways, I'm following the guide at https://github.com/ehough/docker-nfs-server/blob/develop/doc/feature/apparmor.md and when I run step 3 (apparmor_parser) I get the following error

`AppArmor parser error for /opt/nfs/apparmor_nfs.txt in /opt/nfs/apparmor_nfs.txt at line 3: Could not open 'abstractions/lxc/container-base'`

I have the apparmor-utils install and have also tried installing both apparmor-profiles and apparmor-profiles-extra.  no joy

Any help would be greatly appreciated

**Comment by macpijan** [comment]
Hi @choman 
Try installing `lxc`.
I have already included such hint in this PR: https://github.com/ehough/docker-nfs-server/pull/19/files

**Comment by choman** [comment]
That worked, sortof...  Now I'm getting this during the docker run

`mount: mounting rpc_pipefs on /var/lib/nfs/rpc_pipefs failed: Permission denied
----> 
----> ERROR: unable to mount rpc_pipefs filesystem onto /var/lib/nfs/rpc_pipefs
----> 
`

**Comment by ehough** [comment]
@choman could you post your full `docker run` command? or `docker-compose.yml` etc.

> `mount: mounting rpc_pipefs on /var/lib/nfs/rpc_pipefs failed: Permission denied`

Seems to indicate that either the correct AppArmor profile isn't loaded into the kernel, or you're missing the `security-opt` portion of your `docker run` command (i.e. step 4 from the AppArmor guide).

@macpijan I'm so sorry that I haven't yet merged your PR. I promise that I haven't forgotten! It will get done..

**Comment by choman** [comment]
That worked, sortof...  Now I'm getting this during the docker run

`mount: mounting rpc_pipefs on /var/lib/nfs/rpc_pipefs failed: Permission denied
----> 
----> ERROR: unable to mount rpc_pipefs filesystem onto /var/lib/nfs/rpc_pipefs
----> 
`

**Comment by choman** [comment]
secuirty-opt was missing.  Thanks.  off to the next issue

**Comment by choman** [comment]
My docker run command
`docker container run -v /opt/nfs/home:/data            
                          -v /opt/nfs/exports:/etc/exports:ro   
                          --security-opt apparmor=erichough-nfs 
                          --cap-add SYS_ADMIN                   
                          -p 2049:2049 erichough/nfs-server
`

**Comment by ehough** [comment]
> off to the next issue

Were you able to get everything working? You mentioned a "next issue" but your [follow-up comment](https://github.com/ehough/docker-nfs-server/issues/23#issuecomment-478630412) didn't make it clear to me if there was another problem that we needed to address. Let me know!

**Comment by choman** [comment]
So I think I have it working, ssh in to the system works.  but if I log into the system via the desktop I'm hanging then booted.  Still digging into it.  I'll post back if it's docker-nfs related. 

I will say I had to add other ports to the docker container to get this far

**Comment by ehough** [comment]
> I think I have it working ... Still digging into it. I'll post back if it's docker-nfs related.

OK. I'll close this issue for now, but definitely post back with any follow-up questions or trouble.

> I will say I had to add other ports to the docker container to get this far

I'd be interested in hearing what you had to add, just to make sure that the docs or the image isn't missing anything. Thanks!

**Comment by linuxemb** [comment]
@ehough I have the same issue,in order to add security-opt apparmor=erichough-nfs,
--------------------------------------------------------------------------
 sudo apparmor_parser -r -W ./apparmor_file 
AppArmor parser error for ./apparmor_file in ./apparmor_file at line 3: Could not open 'abstractions/lxc/container-base'
-------------------
cat apparmor_file 
#include <tunables/global>
profile erichough-nfs flags=(attach_disconnected,mediate_deleted) {
#include <abstractions/lxc/container-base>
 mount fstype=nfs*,
 mount fstype=rpc_pipefs,
