### ISSUE TITLE
Whether high availability or backup mode is considered

### ISSUE THREAD

**Issue by lanmingle** [ehough/docker-nfs-server#28]
Very good project！Whether high availability or backup mode is considered.

eg:

      
``` bash

      -> nfs1
vip -> 
      -> nfs2

```

ps:

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/high_availability_add-on_administration/ch-nfsserver-haaa

**Comment by ehough** [comment]
Thanks for your question!

TBH I haven't yet considered a cluster scenario, but I can't think of a reason that this wouldn't be possible. Seems like it would just be a matter of setting up Pacemaker, the container networking, and the shared filesystem. I'll leave this ticket open to track further progress on this issue. If you or anyone else makes progress in this regard, please post back here.

> backup mode

Could you help me understand what you mean by "backup mode"? I'm not familiar with this.
