### ISSUE TITLE
Creating own Image from Dockerfile wont work

### ISSUE THREAD

**Issue by Ujkugri** [ehough/docker-nfs-server#66]
Hi,

I build your Dockerfile with the command

````
docker build --rm --no-cache -t nfs-server /location/of/Dockerfile
````

and after that I tried 

```
docker run -it \
 -v /tmp:/var/nfs \
 -v /root/docker-nfs-server/exports.txt:/etc/exports:ro \
 -v /lib/modules:/lib/modules:ro \
 --cap-add SYS_MODULE \
 --cap-add SYS_ADMIN \
 -p 2049:2049   -p 2049:2049/udp   \
 -p 111:111     -p 111:111/udp     \
 -p 32765:32765 -p 32765:32765/udp \
 -p 32767:32767 -p 32767:32767/udp \
 nfs-server
```

But it gets me this error:

````
==================================================================
      SETTING UP ...
==================================================================
---->
----> ERROR: missing CAP_SYS_ADMIN. be sure to run this image with --cap-add SYS_ADMIN or --privileged
---->
````

Is there something I am missing when building your Image? Because if I use your Image, in other Words the Image erichough/nfs-server everything works fine. Problem is, that I need to modify the Dockerfile, so I cant just use your image ....

Hope you can help me

**Comment by xZero707** [comment]
@GentianRrafshi I have submitted the pull request (#67)  that fixes this. If you want it working in meanwhile, you can check out my fork [xZero707/docker-nfs-server](https://github.com/xZero707/docker-nfs-server)

**Comment by Ujkugri** [comment]
That worked. In my point of view, after the pull this issue can be closed.

**Comment by xZero707** [comment]
Glad that this worked for you. I think the issue should remain open until my pull request is merged.

**Comment by fangzi0813** [comment]
@xZero707 I have build image use your fork but I still have this error,I deploy that on kubernetes

**Comment by fangzi0813** [comment]
@xZero707 this is part of my yaml
`spec:
      containers:
        - name: nfs-server
          image: sh-ccr/nfs-server
          ports:
            - containerPort: 2049
          args:
            - "--cap-add SYS_ADMIN"
            - "--cap-add SYS_MODULE"`
