### ISSUE TITLE
Bug with baked exports file

### ISSUE THREAD

**Issue by rivaros** [ehough/docker-nfs-server#9]
Welcome bug on Docker for Windows/OSX

/etc/exports was baked into the Dockerfile
```
root@73347d4a00c3:/# cat /etc/exports
"/share" *(rw,async,no_subtree_check,insecure,all_squash,anonuid=65534,anongid=0)

root@73347d4a00c3:/# /usr/local/bin/entrypoint.sh

==================================================================
      SETTING UP
==================================================================
----> building /etc/exports
----> no valid exports
root@73347d4a00c3:/#
```

**Comment by ehough** [comment]
Thank you for this report and please accept my apologies for only seeing it now! Not sure how I missed the notification.

This indeed looks like a bug. Please stand by for a fix..

**Comment by ehough** [comment]
I'll build it on Docker Hub in the next day or two, pending the outcome of #10. If you'd like to patch your image, you can make the fix found [here](https://github.com/ehough/docker-nfs-server/commit/3c3b58013fcdf5b8b88242d7bc62f738ee0d6d52#diff-b958f585a04af5ee2087610ea7180f34).

Thanks again!

**Comment by ehough** [comment]
FYI this has been built on Docker Hub and is [now available](https://hub.docker.com/r/erichough/nfs-server/tags/) under the `latest` or `1.1.1` tag.
